name: Notion-Discord Webhook
description: Looks for new pages in a Notion database and sends them to a Discord channel
author: Dervex

branding:
  icon: refresh-cw
  color: white

runs:
  using: node20
  main: dist/index.js
