name: Notion-Discord Webhook
description: Looks for new pages in a Notion database and sends them to a Discord channel
author: Dervex

branding:
  icon: refresh-cw
  color: white

inputs:
  NOTION_API_KEY:
    description: Notion integration internal secret
    required: true
  DATABASE_ID:
    description: Target Notion page database ID (located in URL)
    required: true
  WEBHOOK_URL:
    description: Discord channel webhook URL
    required: true

runs:
  using: node20
  main: dist/index.js
