name: Notion-Discord Webhook
description: Looks for new pages in a Notion database and sends them to a Discord channel
author: Dervex

branding:
  icon: refresh-cw
  color: white

inputs:
  NOTION_API_KEY:
    description: Notion integration internal secret
    required: true
  BUGS_DATABASE_ID:
    description: Target bugs Notion database ID (located in URL)
    required: true
  TASKS_DATABASE_ID:
    description: Target tasks Notion database ID (located in URL)
    required: true
  BUGS_WEBHOOK_URL:
    description: Discord bugs channel webhook URL
    required: true
  TASKS_WEBHOOK_URL:
    description: Discord tasks channel webhook URL
    required: true

runs:
  using: node20
  main: dist/index.js
