name: Run Action

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - uses: Rensselaer-County/notion-discord-webhook@0.1.7
        with:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          BUGS_DATABASE_ID: ${{ secrets.BUGS_DATABASE_ID }}
          TASKS_DATABASE_ID: ${{ secrets.TASKS_DATABASE_ID }}
          BUGS_WEBHOOK_URL: ${{ secrets.BUGS_WEBHOOK_URL }}
          TASKS_WEBHOOK_URL: ${{ secrets.TASKS_WEBHOOK_URL }}
